[package]
name = "advent-of-code-2025"
version = "0.1.0"
authors = ["Federico Ravasio <ravasio.federico@gmail.com>"]
edition = "2024"

[lib]
doctest = false
bench = false

[dependencies]
aoc-runner = "~0.3"
aoc-runner-derive = "~0.3"

[profile.release]
lto = "fat"
